on:
  push:
    branches:
      - master

name: Deploy to Amazon EB

jobs:
  dockerize-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dockerize Frontend
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        ENV: production
      with:
        name: liannus/tbwsite
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./frontend
        buildargs: ENV
        tags: "frontend"

  dockerize-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dockerize Backend
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        ENV: production
      with:
        name: liannus/tbwsite
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./backend
        buildargs: ENV 
        tags: "backend"

  dockerize-reverseproxy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dockerize Reverse Proxy
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: liannus/tbwsite
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./reverseproxy
        tags: "reverseproxy"

  deploy:
    needs: [dockerize-frontend, dockerize-backend, dockerize-reverseproxy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - uses: actions/checkout@v1
      - name: install eb-cli
        working-directory: ./
        run: |
          pip install awsebcli --upgrade
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_EB_SECRET_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_EB_SECRET_KEY }}
          ls
          eb init -r ca-central-1 -p "64bit Amazon Linux 2018.03 v2.18.0 running Multi-container Docker 18.09.9-ce (Generic)" TBW-website
          eb deploy
